# Generated by Django 3.2.7 on 2021-09-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('ONE', 1), ('TWO', 2), ('Three', 3)], default='ONE', max_length=20),
        ),
    ]
