# Generated by Django 3.2.7 on 2021-09-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_attemp_point_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
