# Generated by Django 3.2.7 on 2021-09-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_question_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='attempt',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
